export const questionsPool = [
  {
    id: 1,
    question: "What is the chemical symbol for Gold?",
    options: ["Au", "Ag", "Fe", "Cu"],
    correctAnswer: "Au",
  },
  {
    id: 2,
    question: "Which planet is known as the Red Planet?",
    options: ["Mars", "Jupiter", "Saturn", "Venus"],
    correctAnswer: "Mars",
  },
  {
    id: 3,
    question: "What is the main gas found in the air we breathe?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
    correctAnswer: "Nitrogen",
  },
  {
    id: 4,
    question: "Who was the first President of the United States?",
    options: [
      "Thomas Jefferson",
      "Abraham Lincoln",
      "George Washington",
      "John Adams",
    ],
    correctAnswer: "George Washington",
  },
  {
    id: 5,
    question: "In which year did the Titanic sink?",
    options: ["1912", "1905", "1918", "1923"],
    correctAnswer: "1912",
  },
  {
    id: 6,
    question:
      "What ancient civilization built the Machu Picchu complex in Peru?",
    options: ["The Maya", "The Aztecs", "The Incas", "The Olmecs"],
    correctAnswer: "The Incas",
  },
  {
    id: 7,
    question: "What is the value of Pi up to two decimal places?",
    options: ["3.14", "2.15", "3.15", "3.16"],
    correctAnswer: "3.14",
  },
  {
    id: 8,
    question: "What is the square root of 64?",
    options: ["6", "8", "10", "12"],
    correctAnswer: "8",
  },
  {
    id: 9,
    question:
      "If a triangle has angles of 30 and 60 degrees, what is the measure of the third angle?",
    options: ["60 degrees", "90 degrees", "45 degrees", "30 degrees"],
    correctAnswer: "90 degrees",
  },
  {
    id: 10,
    question: "What is the hardest natural substance on Earth?",
    options: ["Diamond", "Quartz", "Ruby", "Graphite"],
    correctAnswer: "Diamond",
  },
  {
    id: 11,
    question: "How many planets are in our solar system?",
    options: ["7", "8", "9", "10"],
    correctAnswer: "8",
  },
  {
    id: 12,
    question:
      "What gas do plants absorb from the atmosphere during photosynthesis?",
    options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Methane"],
    correctAnswer: "Carbon Dioxide",
  },
  {
    id: 13,
    question:
      "Which war was fought between the North and South regions in the United States?",
    options: [
      "World War I",
      "The Civil War",
      "The Revolutionary War",
      "The Vietnam War",
    ],
    correctAnswer: "The Civil War",
  },
  {
    id: 14,
    question: "Who was known as the 'Iron Lady' in British politics?",
    options: [
      "Queen Elizabeth II",
      "Margaret Thatcher",
      "Indira Gandhi",
      "Angela Merkel",
    ],
    correctAnswer: "Margaret Thatcher",
  },
  {
    id: 15,
    question: "Which empire was ruled by Genghis Khan?",
    options: [
      "The Roman Empire",
      "The Ottoman Empire",
      "The Mongol Empire",
      "The British Empire",
    ],
    correctAnswer: "The Mongol Empire",
  },
  {
    id: 16,
    question: "What is the sum of angles in a triangle?",
    options: ["180 degrees", "360 degrees", "90 degrees", "270 degrees"],
    correctAnswer: "180 degrees",
  },
  {
    id: 17,
    question: "What is 15% of 200?",
    options: ["30", "20", "15", "25"],
    correctAnswer: "30",
  },
  {
    id: 18,
    question: "If you divide 50 by half and add 20, what is the result?",
    options: ["45", "70", "120", "100"],
    correctAnswer: "120",
  },
  {
    id: 19,
    question: "What is the capital city of France?",
    options: ["Paris", "London", "Berlin", "Rome"],
    correctAnswer: "Paris",
  },
  {
    id: 20,
    question: "What is the primary language spoken in Brazil?",
    options: ["Spanish", "Portuguese", "English", "French"],
    correctAnswer: "Portuguese",
  },
  {
    id: 21,
    question: "What is the largest planet in our solar system?",
    options: ["Earth", "Jupiter", "Mars", "Saturn"],
    correctAnswer: "Jupiter",
  },
  {
    id: 22,
    question: "What is the boiling point of water in Celsius?",
    options: ["100 degrees", "90 degrees", "80 degrees", "110 degrees"],
    correctAnswer: "100 degrees",
  },
  {
    id: 23,
    question:
      "Which war was fought between the North and South regions in the United States?",
    options: [
      "The Civil War",
      "The Revolutionary War",
      "World War I",
      "The Vietnam War",
    ],
    correctAnswer: "The Civil War",
  },
  {
    id: 24,
    question: "What is the capital of Germany?",
    options: ["Sydney", "Bucharest", "Berlin", "Canberra"],
    correctAnswer: "Berlin",
  },
  {
    id: 25,
    question: "What is the formula for calculating the area of a circle?",
    options: ["πr²", "2πr", "πd", "r²/2"],
    correctAnswer: "πr²",
  },
  {
    id: 26,
    question: "If x = 2 and y = 3, what is x² + y²?",
    options: ["13", "8", "17", "11"],
    correctAnswer: "13",
  },
  {
    id: 27,
    question: "In which continent is the Sahara Desert located?",
    options: ["Africa", "Asia", "Australia", "South America"],
    correctAnswer: "Africa",
  },
  {
    id: 28,
    question: "Which language is primarily spoken in Spain?",
    options: ["Spanish", "French", "Portuguese", "Italian"],
    correctAnswer: "Spanish",
  },
  {
    id: 29,
    question: "What is the main ingredient in sushi?",
    options: ["Fish", "Chicken", "Beef", "Pork"],
    correctAnswer: "Fish",
  },
  {
    id: 30,
    question: "Who is the author of the novel '1984'?",
    options: [
      "George Orwell",
      "Ernest Hemingway",
      "F. Scott Fitzgerald",
      "Mark Twain",
    ],
    correctAnswer: "George Orwell",
  },
  {
    id: 31,
    question: "What is the periodic table symbol for Hydrogen?",
    options: ["H", "He", "Hy", "Ho"],
    correctAnswer: "H",
  },
  {
    id: 32,
    question: "What is the primary source of energy for the Earth?",
    options: ["The Moon", "The Sun", "Wind", "Geothermal sources"],
    correctAnswer: "The Sun",
  },
  {
    id: 33,
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    options: [
      "Amelia Earhart",
      "Harriet Quimby",
      "Bessie Coleman",
      "Valentina Tereshkova",
    ],
    correctAnswer: "Amelia Earhart",
  },
  {
    id: 34,
    question: "In what year did the Berlin Wall fall?",
    options: ["1989", "1971", "1961", "1991"],
    correctAnswer: "1989",
  },
  {
    id: 35,
    question: "What is the name of a polygon with eight sides?",
    options: ["Hexagon", "Octagon", "Decagon", "Heptagon"],
    correctAnswer: "Octagon",
  },
  {
    id: 36,
    question: "What is the value of π (Pi) rounded to three decimal places?",
    options: ["3.141", "3.142", "3.140", "3.143"],
    correctAnswer: "3.141",
  },
  {
    id: 37,
    question: "Which river is the longest in the world?",
    options: ["Nile", "Amazon", "Yangtze", "Mississippi"],
    correctAnswer: "Nile",
  },
  {
    id: 38,
    question: "What is the capital city of Japan?",
    options: ["Tokyo", "Kyoto", "Osaka", "Hiroshima"],
    correctAnswer: "Tokyo",
  },
  {
    id: 39,
    question: "Which vitamin is primarily obtained from sunlight?",
    options: ["Vitamin C", "Vitamin D", "Vitamin B12", "Vitamin A"],
    correctAnswer: "Vitamin D",
  },
  {
    id: 40,
    question:
      "What is the product of the square root of 25 and the square root of 9?",
    options: ["15", "100", "34", "22"],
    correctAnswer: "15",
  },
  {
    id: 41,
    question: "In which country was the ancient city of Carthage located?",
    options: ["Egypt", "Italy", "Greece", "Tunisia"],
    correctAnswer: "Tunisia",
  },
  {
    id: 42,
    question: "What is the mathematical term for a shape with five sides?",
    options: ["Triangle", "Pentagon", "Hexagon", "Octagon"],
    correctAnswer: "Pentagon",
  },
  {
    id: 43,
    question:
      "What is the product of the square root of 16 and the square root of 9?",
    options: ["12", "18", "24", "30"],
    correctAnswer: "12",
  },
  {
    id: 44,
    question: "In what type of biome would you find the Amazon Rainforest?",
    options: ["Desert", "Tundra", "Rainforest", "Savannah"],
    correctAnswer: "Rainforest",
  },
  {
    id: 45,
    question: "Which instrument measures atmospheric pressure?",
    options: ["Thermometer", "Barometer", "Anemometer", "Hygrometer"],
    correctAnswer: "Barometer",
  },
  {
    id: 46,
    question: "What is the capital of Romania?",
    options: ["Sydney", "Bucharest", "Perth", "Canberra"],
    correctAnswer: "Bucharest",
  },
  {
    id: 47,
    question: "In music, what does 'piano' mean?",
    options: ["Loud", "Soft", "Fast", "Slow"],
    correctAnswer: "Soft",
  },
  {
    id: 48,
    question: "What is the term for the speed at which light travels?",
    options: [
      "Speed of Light",
      "Luminal Speed",
      "Photon Velocity",
      "Warp Speed",
    ],
    correctAnswer: "Speed of Light",
  },
  {
    id: 49,
    question: "What is the primary component of natural gas?",
    options: ["Methane", "Ethane", "Propane", "Butane"],
    correctAnswer: "Methane",
  },
  {
    id: 50,
    question: "Who wrote the play 'Hamlet'?",
    options: [
      "William Shakespeare",
      "Christopher Marlowe",
      "John Milton",
      "Ben Jonson",
    ],
    correctAnswer: "William Shakespeare",
  },
];
